### ISSUE TITLE
Fix pathfinding for Board

### ISSUE THREAD

**Issue by clarashong** [clarashong/Quoridor-Analysis#1]
Need to figure out a way to check if there is a valid path for the player to get to the ending row.

**Comment by Jitanshu-commits** [comment]
This is a pseudocode for your problem (I currently dont know why I cannot create a pull request for your issue)
function is_valid_path_exists(grid, start, end):
    # Perform a pathfinding algorithm (e.g., Dijkstra's or A*) to check for a valid path
    visited = set()
    queue = Queue()

    queue.enqueue(start)
    visited.add(start)

    while not queue.isEmpty():
        current = queue.dequeue()

        if current == end:
            # A valid path from start to end is found
            return True

        for neighbor in get_valid_neighbors(current, grid):
            if neighbor not in visited:
                queue.enqueue(neighbor)
                visited.add(neighbor)

    # No valid path from start to end is found
    return False

function get_valid_neighbors(cell, grid):
    x, y = cell
    valid_neighbors = []

    # Consider neighbors to the left, right, and below (assuming movement in one direction)
    if x > 0 and grid[x - 1][y] != obstacle:
        valid_neighbors.append((x - 1, y))
    if x < rows - 1 and grid[x + 1][y] != obstacle:
        valid_neighbors.append((x + 1, y))
    if y < cols - 1 and grid[x][y + 1] != obstacle:
        valid_neighbors.append((x, y + 1))

    return valid_neighbors

# Example usage
grid = [
    [0, 0, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0],
    [0, 1, 1, 1, 1],
    [0, 0, 0, 0, 0]
]
start = (0, 0)
end = (4, 4)

if is_valid_path_exists(grid, start, end):
    print("A valid path exists.")
else:
    print("No valid path exists.")

**Comment by clarashong** [comment]
Thank you! Your solution really helped!
